#Wordpress container
version: '3'
services:
#Database service
  db:
    image: mariadb:latest
#    command: mysqld --innodb-buffer-pool-size=64M    
    container_name: db-${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - "./mysql/datadir:/var/lib/mysql"
      - "./mysql/backup_mysql:/backup:ro"
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro

    networks:
      - default
#docker exec some-mariadb sh -c 'exec mysqldump --all-databases -uroot -p"$MYSQL_ROOT_PASSWORD"' > /some/path/on/your/host/all-databases.sql
#Wordpress service
  drupal:
    image: drupal:8-apache
    container_name: drupal-${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${HOSTNAME}
#     VIRTUAL_PORT: ${VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${HOSTNAME}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
#      DRUPAL_PROFILE: standard
#      DRUPAL_SITE_NAME: Drupal
#      DRUPAL_USER: admin
#      DRUPAL_PASS: admin
#      DRUPAL_DBURL: mysql://drupal:drupal@database:3306/drupal
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

#    ports:
#      - 8080:80
    volumes:
      - "./html/modules:/var/www/html/modules"
      - "./html/profiles:/var/www/html/profiles"
      - "./html/themes:/var/www/html/themes"
      - "./html/sites:/var/www/html/sites"
    depends_on:
      - db
    networks:
      - webproxy
      - default

  adminer:
    container_name: adminer-${CONTAINER_NAME}
    image: adminer
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      ADMINER_DESIGN: "nette"
      ADMINER_PLUGINS: "tables-filter tinymce"

networks:
  webproxy:
    external:
      name: webproxy
